version: '3'

services:
    brevets:
        build: 
          context: brevets/.
          dockerfile: Dockerfile
        ports: 
          - "5001:5000"
        depends_on:
          - mongodb
        environment:
          MONGODB_HOSTNAME: mongodb
    mongodb:
        image: mongo:5.0.5
          
